cloudsimplus/cloudsimplus

- pom.xml
Remove the VersionEye Project ID from the parent pom.xml file. That prevents the API from merging child projects.
> Remove project ID from parent pom.xml

- cloudsim-plus-examples/src/main/java/org/cloudsimplus/examples/migration/MigrationExample1.java
- cloudsim-plus-examples/src/main/java/org/cloudsimplus/examples/migration/MigrationExample2_PowerUsage.java
- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/allocationpolicies/migration/VmAllocationPolicyMigration.java
- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/allocationpolicies/migration/VmAllocationPolicyMigrationAbstract.java
- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/allocationpolicies/migration/VmAllocationPolicyMigrationBestFitStaticThreshold.java
- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/allocationpolicies/migration/VmAllocationPolicyMigrationStaticThreshold.java
- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/provisioners/PeProvisioner.java
- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/provisioners/PeProvisionerSimple.java
- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/provisioners/ResourceProvisioner.java
- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/provisioners/ResourceProvisionerAbstract.java
- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/provisioners/ResourceProvisionerSimple.java
- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/utilizationmodels/UtilizationModelDynamic.java
- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/vms/Vm.java
- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/vms/VmNull.java
- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/vms/VmSimple.java
- Updates MigrationExample1 documentation and refactors VmAllocationPolicyMigration.
- Updates ResourceProvisioner documentation.
- Adds getTotalCpuMipsUsage() to Vm to get the current total MIPS used across all virtual PEs.
> Improves docs and adds Vm.getTotalCpuMipsUsage()

- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/datacenters/DatacenterSimple.java
- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/resources/FileStorage.java
- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/resources/HarddriveStorage.java
- Adds the `hasFile(String fileName)` method to the `FileStorage` class to check if a storage device has a specific file.
- Adds the `double getTransferTime(String fileName)` method to the `FileStorage` class to get the time to transfer a file from the device. If the file is not found, the method returns `FileStorage.FILE_NOT_FOUND`.
- Refactor `DatacenterSimple.predictFileTransferTime` to use the new `FileStorage` `getTransferTime(String fileName)` method, making just one call to get the file transfer time (moving the complexity of first trying to get the file to the `HarddriveStorage` class).
> Refactor FileStorage and file transfer time computation.

- cloudsim-plus-examples/src/main/java/org/cloudsimplus/examples/StorageAreaNetworkExample1.java
- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/datacenters/Datacenter.java
- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/datacenters/DatacenterNull.java
- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/datacenters/DatacenterSimple.java
- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/resources/DatacenterStorage.java
- cloudsim-plus/src/main/java/org/cloudsimplus/builders/DatacenterBuilder.java
- cloudsim-plus/src/test/java/org/cloudbus/cloudsim/datacenters/DatacenterTest.java
DatacenterSimple had:
1.the storageList attribute, getter and setter
2.addFile and the two contains methods
3.setAllFilesOfAllStoragesToThisDatacenter method
4.predictFileTransferTime and timeToTransferFileFromStorage
,all moved to new class DatacenterStorage in resources package (had to change the name since the new object is not a list its an object that has a list so naming it StorageList will create too much confusion!)
DatacenterSimple has now a new object of DatacenterStorage with getter and setter
This implied changes to the following classes:
DatacenterNull
Datacenter (since it has prototypes of getter and setter of the moved storageList)
DatacenterBuilder
StorageAreaNetworkExample1
DatacenterTest
Allow edits from maintainers was checked for this pull request
> Closes #141

- cloudsim-plus-testbeds/src/main/java/org/cloudsimplus/testbeds/linuxscheduler/CloudletSchedulerTimeSharedRunner.java
- cloudsim-plus-testbeds/src/main/java/org/cloudsimplus/testbeds/linuxscheduler/CompletelyFairSchedulerRunner.java
This pull request fixes an out of bounds error in `seeds` (`ArrayList`) at [ExperimentRunner.java#L456](https://github.com/manoelcampos/cloudsim-plus/blob/981b8df95e60cc321f3c91ea06045ace7c15d5ba/cloudsim-plus-testbeds/src/main/java/org/cloudsimplus/testbeds/ExperimentRunner.java#L456). This error is caused because the `createExperiment` functions in `linuxscheduler` module tried creating a random number (`createRandomGen`) before an experiment construction. Since the `seeds` (`ArrayList`) is only populated after the experiment construction, the getter of seeds in [`createRandomGen`](https://github.com/manoelcampos/cloudsim-plus/blob/981b8df95e60cc321f3c91ea06045ace7c15d5ba/cloudsim-plus-testbeds/src/main/java/org/cloudsimplus/testbeds/ExperimentRunner.java#L456) throws …
> Fixed out of bounds error in `seeds` (`ArrayList`)

- cloudsim-plus-examples/src/main/java/org/cloudsimplus/examples/brokers/DatacenterBrokerHeuristicExample.java
- cloudsim-plus/src/main/java/org/cloudsimplus/heuristics/CloudletToVmMappingSolution.java
- cloudsim-plus/src/main/java/org/cloudsimplus/heuristics/Heuristic.java
- cloudsim-plus/src/main/java/org/cloudsimplus/heuristics/SimulatedAnnealing.java
This PR fixes bug in `createListWithTwoRandomEntries` the loop index `i` (see [here](https://github.com/manoelcampos/cloudsim-plus/blob/c8bdcf4181e485d570592ffc5c3b1e9212e976ac/cloudsim-plus/src/main/java/org/cloudsimplus/heuristics/CloudletToVmMappingSolution.java#L352)) was never incremented, thus the two random entries were never selected.
Additionally, following minor fixes are also pushed:
- Add Logger in `Heuristic` classes.
- Fixed typos in `DatacenterBrokerHeuristicExample`
- Remove package name before the `DatacenterBrokerHeuristic` class name. Not needed since the example name has no conflicts now.
> Fixes a bug in selecting random entries in CloudletToVmMappingSolution

- cloudsim-plus-examples/src/main/java/org/cloudsimplus/examples/brokers/CloudletToVmMappingBestFit.java
- cloudsim-plus-examples/src/main/java/org/cloudsimplus/examples/brokers/DatacenterBrokerHeuristicExample.java
- cloudsim-plus-examples/src/main/java/org/cloudsimplus/examples/brokers/DatacenterBrokersMappingComparison.java
- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/brokers/DatacenterBrokerAbstract.java
- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/brokers/DatacenterBrokerBestFit.java
- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/brokers/DatacenterBrokerHeuristic.java
- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/brokers/DatacenterBrokerSimple.java
- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/cloudlets/Cloudlet.java
- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/cloudlets/CloudletAbstract.java
- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/cloudlets/CloudletNull.java
- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/cloudlets/network/CloudletSendTask.java
- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/schedulers/cloudlet/CloudletSchedulerAbstract.java
- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/vms/Vm.java
- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/vms/VmNull.java
- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/vms/VmSimple.java
- cloudsim-plus/src/main/java/org/cloudsimplus/heuristics/HeuristicSolution.java
- cloudsim-plus/src/test/java/org/cloudbus/cloudsim/cloudlets/CloudletTest.java
This PR adds `DatacenterBrokerBestFit`, another implementation of `DatacenterBroker` with a best fit cloudlet-VM mapper (best fit in a truer sense ;) ). This is different from the approach in [`bestFitCloudletToVmMapper()`](https://github.com/humaira-salam/cloudsim-plus/blob/d0ff7dbda7f5e6d641e78bfe5c84f99205c508a6/cloudsim-plus-examples/src/main/java/org/cloudsimplus/examples/brokers/CloudletToVmMappingBestFit.java#L130
) (in example: `CloudletToVmMappingBestFit`), because the `DatacenterBroker` maps a `Cloudlet` to a `Vm` without checking if the `Pe`s in the `Vm` are already being reserved by other `Cloudlet`s. This is easily reproducible with the case when number of `Cloudlet`s are more than `Vm`s. Also, the inherent behavior of java `Stream`'s `min()` method causes the same `Vm` to be …
> Adds DatacenterBrokerBestFit, an implementation of DatacenterBroker with a best fit Cloudlet to VM mapper

- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/core/CloudSim.java
- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/core/CloudSimEntity.java
- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/core/Simulation.java
- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/core/SimulationNull.java
- pom.xml
The purpose is to introduce synchronous control over execution of the simulation (being able to set the simulation in the "running" state and then move it forward step by step as needed).
Most of the changes are in the `CloudSim` class. You can start at `startSync`, `finalizeSimulation` and `runFor` and it should get your through all additional methods.
I can provide some if you want to go in this direction.
https://github.com/manoelcampos/cloudsim-plus/issues/205
Nope - just let me know what you think. If this is a direction you are interested in merging let me know what should I add/change to get it to a "merge-able" state.
> Introduce sync execution of the simulation

- cloudsim-plus-examples/src/main/java/org/cloudsimplus/examples/power/PowerExample.java
- cloudsim-plus-examples/src/main/java/org/cloudsimplus/examples/power/PowerExampleSchedulingInterval.java
This only contains fixes in the documentation, comments, and variable names of two examples. Many times Watt-Seconds (energy) were used when the correct physical entity is just Watt (power).
> Unified and corrected the use of physical units in the PowerExamples

- README.md
This PR fixes a minor error that exists in README's 5th section that gives Java code for a minimal simulation scenario. 
As seen here:
```java
//Creates Cloudlets that represent applications to be run inside a VM.
List<Cloudlet> cloudletList = new ArrayList<>(1);
//UtilizationModel defining the Cloudlets use only 50% of any resource all the time
UtilizationModelDynamic utilizationModel = new UtilizationModelDynamic(0.5);
Cloudlet cloudlet0 = new CloudletSimple(10000, 1, utilizationModel);
Cloudlet cloudlet1 = new CloudletSimple(10000, 1, utilizationModel);
cloudlets.add(cloudlet0);
cloudlets.add(cloudlet1);
```
`cloudletList` is mispelled in add operations as `cloudlets` resulting in a compilation error.
> Fixes README's section 5  minimal simulation scenario

- cloudsim-plus-examples/src/main/java/org/cloudbus/cloudsim/examples/network/NetworkExample1.java
- cloudsim-plus-examples/src/main/java/org/cloudbus/cloudsim/examples/network/NetworkExample2.java
- cloudsim-plus-examples/src/main/java/org/cloudbus/cloudsim/examples/network/NetworkExample3.java
- cloudsim-plus-examples/src/main/java/org/cloudbus/cloudsim/examples/network/NetworkExample4.java
- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/core/CloudSimEntity.java
- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/network/topologies/BriteNetworkTopology.java
- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/network/topologies/NetworkTopology.java
- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/network/topologies/NetworkTopologyNull.java
First step towards refactoring the network API (#261).
So far it was based on the IDs of SimEntitys, now users can pass the SimEntitys directly.
> Migrating network API from id-based to object-based

- cloudsim-plus-examples/src/main/java/org/cloudbus/cloudsim/examples/network/NetworkExample1.java
- cloudsim-plus-examples/src/main/java/org/cloudbus/cloudsim/examples/network/NetworkExample2.java
- cloudsim-plus-examples/src/main/java/org/cloudbus/cloudsim/examples/network/NetworkExample3.java
- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/network/topologies/BriteNetworkTopology.java
- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/network/topologies/NetworkTopology.java
- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/network/topologies/NetworkTopologyNull.java
The NetworkTopology interface contained several methods that were specific to Brite topologies.
On the other hand, a removeLink() method was missing.
> Removed Brite-specific methods from NetworkTopology interface

- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/power/PowerMeter.java
- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/power/models/PowerModelDatacenterNull.java
- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/power/models/PowerModelHostNull.java
- default `measurementInterval` is now 1 instead of 0
- `setMeasurementInterval()` returns "this" for method chaning
- Implemented missing methods in `PowerModelDatacenterNull` and `PowerModelHostNull`
> Minor improvements to power package

- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/core/CloudSim.java
When working with many concurrent events the previous solution was regularly throwing `ConcurrentModificationException`s.
The new implementation is simpler and just walks the future event queue until the time on an event is not equal to the time of the first event.
> avoid ConcurrentModificationException in event loop

- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/power/PowerMeter.java
Only re-schedule power measurements if there are other events to be processed
> Bugfix: PowerMeter was re-scheduling events indefinitely

- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/power/PowerMeasurement.java
- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/power/models/PowerModel.java
- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/power/models/PowerModelHostSimple.java
The PowerMeasurement constructor is not to be confused with the validation taking place in PowerModels where the fields are "maxPower" and "staticPower" (where "staticPower" can be ambiguous).
In PowerMeasurement we have two absolute values "staticUsage" and "dynamicUsage", that are also expected to be valid when they are between 0 and 1.
> PowerMeasurement fields don't need to be validated

- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/allocationpolicies/VmAllocationPolicyBestFit.java
- cloudsim-plus/src/main/java/org/cloudbus/cloudsim/allocationpolicies/VmAllocationPolicyWorstFit.java
The first sentence for VmAllocationPolicyBestFit is wrong. "Best Fit" is
used to replace "Worst Fit."
The latter parts of the first sentences are also revised for better
understanding.
> Update some comments in some VmAllocationPolicies

- cloudsim-plus-examples/src/main/java/org/cloudsimplus/examples/costs/CostsExample1.java
This pull request fixes the CostsExample1.java.
The VMs number exceeded the allocation of PEs and the example crashes.
Indeed with
HOST_PES = 8;
VM_PES = 4;
And
VMS = 6;
CloudSim Plus is not able to allocate 4 VM_PES to 6 VMS.
Before the fix:
private static final int VMS = 6;
After the fix:
private static final int VMS = 4;
private static final int VMS = 4;
> [FIX]: Infinite retry to create failed VMs in CostsExample1

- src/main/java/org/cloudbus/cloudsim/brokers/DatacenterBroker.java
- src/main/java/org/cloudbus/cloudsim/brokers/DatacenterBrokerAbstract.java
- src/main/java/org/cloudbus/cloudsim/brokers/DatacenterBrokerNull.java
- src/main/java/org/cloudbus/cloudsim/brokers/VmCreation.java
- src/main/java/org/cloudbus/cloudsim/brokers/VmCreationRetry.java
- src/test/java/org/cloudsimplus/integrationtests/VmCreationFailureIntegrationTest.java
2 New attributes `maxVmCreationRetries` and `currentVmCreationRetries` are created to keep track of the number of retry requests sent in DataBroker.java. The`maxVmCreationRetries` conforms with `failedVmsRetryDelay` and every time a new creation retry request is sent `currentVmCreationRetries` is incremented.
Once all the VMs are allocated and `vmWaitingList` is empty, `currentVmCreationRetries` is set to default to the value of 1.
> Fix #349: Added VM Retry Counter & the functionalities to set it to default

- src/main/java/org/cloudsimplus/schedulers/cloudlet/CloudletSchedulerAbstract.java
- src/test/java/org/cloudsimplus/integrationtests/CloudletLifeTimeTest.java
However, there is still an open question regarding `getCloudletProcessingUpdateInterval()` in `DatacenterSimple.java` and the return value if schedulingInterval > 0. I believe that `delay` should be returned, instead of `min(delay, nextFinishingTime)`, as the datacenter wouldn't be able to detect the end of the cloudlet's life before the next scheduling "tick". Let me know if such behavior makes sense to you, and I'll provide a related additional commit.
> Consider lifeTime in the scheduling interval of a datacenter (Issue #476)

- src/main/java/org/cloudsimplus/brokers/DatacenterBrokerAbstract.java
- src/main/java/org/cloudsimplus/core/CustomerEntity.java
- src/main/java/org/cloudsimplus/core/CustomerEntityAbstract.java
- src/test/java/org/cloudsimplus/mocks/CloudSimMocker.java
- src/test/java/org/cloudsimplus/schedulers/cloudlet/CloudletSchedulerTimeSharedTest.java
- src/test/java/org/cloudsimplus/utilizationmodels/TestUtility.java
- src/test/java/org/cloudsimplus/vms/VmCreationTimeTest.java
- src/test/java/org/cloudsimplus/vms/VmIdleIntervalTest.java
- src/test/java/org/cloudsimplus/vms/VmSimpleTest.java
bug: Fix creation and wait time computation when a finished VM is re-submitted to the broker
Close #351
> Close #351
